### ISSUE TITLE
[Bug] Errores al ejecutar las funciones de fibonacci

### ISSUE THREAD

**Issue by islasjuanp** [gosella/dsl-tp2#15]
La función de fibonacci esta diseñada para recibir un valor n como parámetro y retornar el valor enésimo. Sin embargo, un error en el uso de esta función tal como pesarla un numero negativo generara una recursion infinita.

**Comment by gosella** [comment]
Es cierto, no se valida que el argumento sea un número entero positivo.

Corregido en a5aad5861c79fe8d5aa46f96004dbdb5c8d17857.
