### ISSUE TITLE
[Enhancement] Mejorar la performance para fibonacci

### ISSUE THREAD

**Issue by islasjuanp** [gosella/dsl-tp2#16]
La solución recursiva de la función de fibonacci puede llegar a consumir muchos recursos. Seria bueno cambiar la implementan de la función con recursividad de cola para poder así evitar posibles desbordamientos de pila, como así también, poder aumentar el numero de valores posibles que puede calcular la función.

**Comment by gosella** [comment]
Intencionalmente es la peor implementación posible para el cálculo de los números de Fibonacci 😃 
Por favor, mirá el comentario en #18 para ver que se puede hacer.

**Comment by islasjuanp** [comment]
Acabo de hacer las correcciones sugeridas en el PR #18  para poder mantener las diferentes implementaciones recursivas. Espero que puedas darle una mirada y decirme que opinas :smile:

**Comment by gosella** [comment]
Hecho el merge del PR #18.
