### ISSUE TITLE
[Question] Como ejecutar el proyecto

### ISSUE THREAD

**Issue by islasjuanp** [gosella/dsl-tp2#17]
Algunos de los archivos son de facil ejecucion (por ejemplo las soluciones implementadas en python). Otras, por el contrario, requieren una preparación del entorno de desarrollo para ser ejecutadas. 
¿Podriamos armar una explicacion sobre como preparar el ambiente para poder integrar a nuevos desarrolladores mas rapidamente?

**Comment by gosella** [comment]
¿Se ofrece un PR? 😉

**Comment by islasjuanp** [comment]
Seguro, el PR #18 Incluye un ejemplo de como ejecutar los módulos en python para poder probarlos de forma rápida.

**Comment by gosella** [comment]
Hecho el merge del PR #18.
